### ISSUE TITLE
RuntimeError: Parent directory output does not exist.

### ISSUE THREAD

**Issue by sheldonxxd** [SSDL-SNU/DeepSNUPI#1]
A minor bug. 
I have found that the **output** folder must be created inside `DeepSNUPI` before usage. 
Maybe it's more convinient to update the `DeepSNUPI.py` to create `output` folder automatically when start running the model.

**Comment by SSDL-SNU** [comment]
Dear sheldonxxd,

Thank you very much for your comment,
The empty output folder was automatically deleted when we uploaded DeepSNUPI to Git Hub, we are so sorry about this inconvenience.
I created an output folder for more convenience.

Thank you again and best regards,
